# Generated by Django 5.0.6 on 2024-06-10 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_side', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
